/* Problem 44: Pentagon numbers
 * By: Mark Guerra
 * 12/16/2015
 */

#ifndef PROBLEM_044_H
#define PROBLEM_044_H

/*
 * Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
 *
 * 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
 *
 * It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
 *
 * Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are
 * pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
 */

namespace problem044 {
    bool isPentagonal(int x);
    int pentagonalNumber(int n);
    int getAnswer();
}

#endif