/* Problem 2: Even Fibonacci numbers
 * By: Mark Guerra
 * 10/19/2015
 */

#ifndef PROBLEM_002_H
#define PROBLEM_002_H

#include <vector>

// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.

namespace problem002 {
    bool isOdd(int i);
    std::vector<int> getFibNumbers(int max);
    int getAnswer();
}

#endif
